=== jthy/WBA2/WBA2/bin/Aufgabe3d.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Chefkoch">
<xs:complexType>
<xs:sequence>
<xs:element name="Rezept">
<xs:complexType>
<xs:sequence>
	<xs:element name="Allgemeines">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Rezeptname" type="xs:string"/>
				<xs:element name="Autor" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>	
	</xs:element>
	
	<xs:element name="Zutaten">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Zutat" type="xs:string"/>
				<xs:element name="Gewicht" type="xs:integer"/>
				<xs:element name="Einheit" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	

	<xs:element name="Portionen">
		<xs:simpleType>
 		   <xs:restriction base="xs:integer">
      			<xs:minInclusive value="0"/>
      			<xs:maxInclusive value="20"/>
    		</xs:restriction>
  		</xs:simpleType>
	</xs:element>
		
		
	<xs:element name="Zubereitung">
		<xs:complexType>
			<xs:sequence>	
				<xs:element name="Arbeitszeit" type="xs:time"/>
				<xs:element name="Schwierigkeitsgrad" type="xs:string"/>
				<xs:element name="Brennwert-p.P" type="xs:integer"/>
				<xs:element name="VorgÃ¤nge" type="xs:string"/>	
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
			
	<xs:element name="Kommentieren">	
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Name" type="xs:string"/>
				<xs:element name="Datum" type="xs:date"/>
				<xs:element name="Zeit" type="xs:time"/>
				<xs:element name="Kommentare" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="Kommentar_hilfreich">
  					<xs:simpleType>
   						<xs:restriction base="xs:string">
   							<xs:pattern value="ja|nein"/>
 						</xs:restriction>
					</xs:simpleType>
			</xs:attribute>
		</xs:complexType>			
	</xs:element>
	
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== jthy/WBA2/WBA2/src/Aufgabe3dPilav.xml
<?xml version="1.0" encoding="UTF-8"?>
<Rezept xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3d.xsd">
  <Allgemeines>
    <Rezeptname>Pilav</Rezeptname>
    <Autor>Vlar</Autor>
  </Allgemeines>
    <Zutaten>
    <Zutat>Reis</Zutat>
    <Gewicht>4</Gewicht>
    <Einheit>Gläser</Einheit>
    
    <Zutat>Nudeln (Vermicelles, Pasta da minestra)</Zutat>
    <Gewicht>1</Gewicht>
    <Einheit>Glas</Einheit>
    
     <Zutat>Wasser</Zutat>
    <Gewicht>8</Gewicht>
    <Einheit>Gläser</Einheit>
    
     <Zutat>Planzenöl</Zutat>
    <Gewicht></Gewicht>
    <Einheit></Einheit>
    
     <Zutat>Salz</Zutat>
    <Gewicht></Gewicht>
    <Einheit></Einheit>
   
  </Zutaten>
  <Portionen>0</Portionen>
  <Zubereitung>
    <Arbeitszeit>00:10:00</Arbeitszeit>
    <Schwierigkeitsgrad>normal</Schwierigkeitsgrad>
    <Brennwert-p.P></Brennwert-p.P>
    <Vorgänge>
    Reis in einem feinen Sieb waschen und abtropfen lassen. 
    In die Pfanne reichlich Pflanzenöl geben, so dass ein Spiegel aus Öl entsteht. 
    Die Nudeln zufügen, goldgelb anbraten, den Reis zufügen und umrühren. 
    Mit kaltem Wasser abschrecken und Salz hinzufügen. 
    Bis zum Siedepunkt köcheln lassen, Herd ausmachen, 
    Deckel darauf legen und ausquellen lassen. 
	Tipp: Man kann in das Wasser noch Curry, Hühnerbrühe oder 
	Rinderbrühe geben, je nachdem wozu man den Reis servieren will.
	</Vorgänge>
  </Zubereitung>
  <Kommentieren Kommentar_hilfreich="ja">
    <Name>küchenmungo</Name>
    <Datum>2010-06-23</Datum>
    <Zeit>14:46:00</Zeit>
    <Kommentare>Hallo ince, 
Dein Reisrezept hört sich gut an. Nimmst Du Langkorn- oder Rundkornreis? 
Sind die Nudel nach dem garen noch zu erkennen? 
Liebe Grüße Renate</Kommentare>
  </Kommentieren>
</Rezept>

=== jthy/WBA2/WBA2/bin/Aufgabe3d.xml
<?xml version="1.0" encoding="UTF-8"?>
<Chefkoch xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Aufgabe3d.xsd">
  <Rezept>
    <Allgemeines>
      <Rezeptname>Rezeptname</Rezeptname>
      <Autor>Autor</Autor>
    </Allgemeines>
    <Zutaten>
      <Zutat>Zutat</Zutat>
      <Gewicht>0</Gewicht>
      <Einheit>Einheit</Einheit>
    </Zutaten>
    <Portionen>0</Portionen>
    <Zubereitung>
      <Arbeitszeit>12:00:00</Arbeitszeit>
      <Schwierigkeitsgrad>Schwierigkeitsgrad</Schwierigkeitsgrad>
      <Brennwert-p.P>0</Brennwert-p.P>
      <Vorgänge>Vorgänge</Vorgänge>
    </Zubereitung>
    <Kommentieren>
      <Name>Name</Name>
      <Datum>2001-01-01</Datum>
      <Zeit>12:00:00</Zeit>
      <Kommentare>Kommentare</Kommentare>
    </Kommentieren>
  </Rezept>
</Chefkoch>
